#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xED2ED19F85B3682C (mattst88@gmail.com)
#
Name     : libXaw
Version  : 1.0.14
Release  : 5
URL      : https://www.x.org/releases/individual/lib/libXaw-1.0.14.tar.bz2
Source0  : https://www.x.org/releases/individual/lib/libXaw-1.0.14.tar.bz2
Source1  : https://www.x.org/releases/individual/lib/libXaw-1.0.14.tar.bz2.sig
Summary  : X Athena Widgets Library, version 6
Group    : Development/Tools
License  : ICU MIT-Opengroup NTP
Requires: libXaw-lib = %{version}-%{release}
Requires: libXaw-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libXpm-dev32
BuildRequires : libxslt-bin
BuildRequires : pkg-config
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xmu)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xpm)
BuildRequires : pkgconfig(32xproto)
BuildRequires : pkgconfig(32xt)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xmu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xpm)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xt)
BuildRequires : xmlto

%description
Xaw is the X Athena Widget Set.
Xaw is a widget set based on the X Toolkit Intrinsics (Xt) Library.

%package dev
Summary: dev components for the libXaw package.
Group: Development
Requires: libXaw-lib = %{version}-%{release}
Provides: libXaw-devel = %{version}-%{release}
Requires: libXaw = %{version}-%{release}

%description dev
dev components for the libXaw package.


%package dev32
Summary: dev32 components for the libXaw package.
Group: Default
Requires: libXaw-lib32 = %{version}-%{release}
Requires: libXaw-dev = %{version}-%{release}

%description dev32
dev32 components for the libXaw package.


%package doc
Summary: doc components for the libXaw package.
Group: Documentation

%description doc
doc components for the libXaw package.


%package lib
Summary: lib components for the libXaw package.
Group: Libraries
Requires: libXaw-license = %{version}-%{release}

%description lib
lib components for the libXaw package.


%package lib32
Summary: lib32 components for the libXaw package.
Group: Default
Requires: libXaw-license = %{version}-%{release}

%description lib32
lib32 components for the libXaw package.


%package license
Summary: license components for the libXaw package.
Group: Default

%description license
license components for the libXaw package.


%prep
%setup -q -n libXaw-1.0.14
cd %{_builddir}/libXaw-1.0.14
pushd ..
cp -a libXaw-1.0.14 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617043024
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1617043024
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXaw
cp %{_builddir}/libXaw-1.0.14/COPYING %{buildroot}/usr/share/package-licenses/libXaw/715a897b37b8e535c5812e5f4e663c30b5a67115
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xaw/AllWidgets.h
/usr/include/X11/Xaw/AsciiSink.h
/usr/include/X11/Xaw/AsciiSinkP.h
/usr/include/X11/Xaw/AsciiSrc.h
/usr/include/X11/Xaw/AsciiSrcP.h
/usr/include/X11/Xaw/AsciiText.h
/usr/include/X11/Xaw/AsciiTextP.h
/usr/include/X11/Xaw/Box.h
/usr/include/X11/Xaw/BoxP.h
/usr/include/X11/Xaw/Cardinals.h
/usr/include/X11/Xaw/Command.h
/usr/include/X11/Xaw/CommandP.h
/usr/include/X11/Xaw/Dialog.h
/usr/include/X11/Xaw/DialogP.h
/usr/include/X11/Xaw/Form.h
/usr/include/X11/Xaw/FormP.h
/usr/include/X11/Xaw/Grip.h
/usr/include/X11/Xaw/GripP.h
/usr/include/X11/Xaw/Label.h
/usr/include/X11/Xaw/LabelP.h
/usr/include/X11/Xaw/List.h
/usr/include/X11/Xaw/ListP.h
/usr/include/X11/Xaw/MenuButtoP.h
/usr/include/X11/Xaw/MenuButton.h
/usr/include/X11/Xaw/MultiSink.h
/usr/include/X11/Xaw/MultiSinkP.h
/usr/include/X11/Xaw/MultiSrc.h
/usr/include/X11/Xaw/MultiSrcP.h
/usr/include/X11/Xaw/Paned.h
/usr/include/X11/Xaw/PanedP.h
/usr/include/X11/Xaw/Panner.h
/usr/include/X11/Xaw/PannerP.h
/usr/include/X11/Xaw/Porthole.h
/usr/include/X11/Xaw/PortholeP.h
/usr/include/X11/Xaw/Repeater.h
/usr/include/X11/Xaw/RepeaterP.h
/usr/include/X11/Xaw/Reports.h
/usr/include/X11/Xaw/Scrollbar.h
/usr/include/X11/Xaw/ScrollbarP.h
/usr/include/X11/Xaw/Simple.h
/usr/include/X11/Xaw/SimpleMenP.h
/usr/include/X11/Xaw/SimpleMenu.h
/usr/include/X11/Xaw/SimpleP.h
/usr/include/X11/Xaw/Sme.h
/usr/include/X11/Xaw/SmeBSB.h
/usr/include/X11/Xaw/SmeBSBP.h
/usr/include/X11/Xaw/SmeLine.h
/usr/include/X11/Xaw/SmeLineP.h
/usr/include/X11/Xaw/SmeP.h
/usr/include/X11/Xaw/StripCharP.h
/usr/include/X11/Xaw/StripChart.h
/usr/include/X11/Xaw/Template.c
/usr/include/X11/Xaw/Template.h
/usr/include/X11/Xaw/TemplateP.h
/usr/include/X11/Xaw/Text.h
/usr/include/X11/Xaw/TextP.h
/usr/include/X11/Xaw/TextSink.h
/usr/include/X11/Xaw/TextSinkP.h
/usr/include/X11/Xaw/TextSrc.h
/usr/include/X11/Xaw/TextSrcP.h
/usr/include/X11/Xaw/Tip.h
/usr/include/X11/Xaw/TipP.h
/usr/include/X11/Xaw/Toggle.h
/usr/include/X11/Xaw/ToggleP.h
/usr/include/X11/Xaw/Tree.h
/usr/include/X11/Xaw/TreeP.h
/usr/include/X11/Xaw/VendorEP.h
/usr/include/X11/Xaw/Viewport.h
/usr/include/X11/Xaw/ViewportP.h
/usr/include/X11/Xaw/XawImP.h
/usr/include/X11/Xaw/XawInit.h
/usr/lib64/libXaw.so
/usr/lib64/libXaw6.so
/usr/lib64/libXaw7.so
/usr/lib64/pkgconfig/xaw6.pc
/usr/lib64/pkgconfig/xaw7.pc
/usr/share/man/man3/Xaw.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXaw.so
/usr/lib32/libXaw6.so
/usr/lib32/libXaw7.so
/usr/lib32/pkgconfig/32xaw6.pc
/usr/lib32/pkgconfig/32xaw7.pc
/usr/lib32/pkgconfig/xaw6.pc
/usr/lib32/pkgconfig/xaw7.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libXaw/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXaw.so.6
/usr/lib64/libXaw.so.7
/usr/lib64/libXaw6.so.6
/usr/lib64/libXaw6.so.6.0.1
/usr/lib64/libXaw7.so.7
/usr/lib64/libXaw7.so.7.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXaw.so.6
/usr/lib32/libXaw.so.7
/usr/lib32/libXaw6.so.6
/usr/lib32/libXaw6.so.6.0.1
/usr/lib32/libXaw7.so.7
/usr/lib32/libXaw7.so.7.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXaw/715a897b37b8e535c5812e5f4e663c30b5a67115
