#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libXaw
Version  : 1.0.13
Release  : 2
URL      : https://www.x.org/releases/individual/lib/libXaw-1.0.13.tar.bz2
Source0  : https://www.x.org/releases/individual/lib/libXaw-1.0.13.tar.bz2
Source99 : https://www.x.org/releases/individual/lib/libXaw-1.0.13.tar.bz2.sig
Summary  : X11 Athena Widget library
Group    : Development/Tools
License  : ICU MIT-Opengroup NTP
Requires: libXaw-lib = %{version}-%{release}
Requires: libXaw-license = %{version}-%{release}
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xmu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xpm)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xt)
BuildRequires : xmlto

%description
Xaw is the X Athena Widget Set.
Xaw is a widget set based on the X Toolkit Intrinsics (Xt) Library.

%package dev
Summary: dev components for the libXaw package.
Group: Development
Requires: libXaw-lib = %{version}-%{release}
Provides: libXaw-devel = %{version}-%{release}
Requires: libXaw = %{version}-%{release}

%description dev
dev components for the libXaw package.


%package doc
Summary: doc components for the libXaw package.
Group: Documentation

%description doc
doc components for the libXaw package.


%package lib
Summary: lib components for the libXaw package.
Group: Libraries
Requires: libXaw-license = %{version}-%{release}

%description lib
lib components for the libXaw package.


%package license
Summary: license components for the libXaw package.
Group: Default

%description license
license components for the libXaw package.


%prep
%setup -q -n libXaw-1.0.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557080112
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fcf-protection=full -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong "
export FCFLAGS="$CFLAGS -O3 -Os -fcf-protection=full -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong "
export FFLAGS="$CFLAGS -O3 -Os -fcf-protection=full -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fcf-protection=full -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1557080112
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXaw
cp COPYING %{buildroot}/usr/share/package-licenses/libXaw/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xaw/AllWidgets.h
/usr/include/X11/Xaw/AsciiSink.h
/usr/include/X11/Xaw/AsciiSinkP.h
/usr/include/X11/Xaw/AsciiSrc.h
/usr/include/X11/Xaw/AsciiSrcP.h
/usr/include/X11/Xaw/AsciiText.h
/usr/include/X11/Xaw/AsciiTextP.h
/usr/include/X11/Xaw/Box.h
/usr/include/X11/Xaw/BoxP.h
/usr/include/X11/Xaw/Cardinals.h
/usr/include/X11/Xaw/Command.h
/usr/include/X11/Xaw/CommandP.h
/usr/include/X11/Xaw/Dialog.h
/usr/include/X11/Xaw/DialogP.h
/usr/include/X11/Xaw/Form.h
/usr/include/X11/Xaw/FormP.h
/usr/include/X11/Xaw/Grip.h
/usr/include/X11/Xaw/GripP.h
/usr/include/X11/Xaw/Label.h
/usr/include/X11/Xaw/LabelP.h
/usr/include/X11/Xaw/List.h
/usr/include/X11/Xaw/ListP.h
/usr/include/X11/Xaw/MenuButtoP.h
/usr/include/X11/Xaw/MenuButton.h
/usr/include/X11/Xaw/MultiSink.h
/usr/include/X11/Xaw/MultiSinkP.h
/usr/include/X11/Xaw/MultiSrc.h
/usr/include/X11/Xaw/MultiSrcP.h
/usr/include/X11/Xaw/Paned.h
/usr/include/X11/Xaw/PanedP.h
/usr/include/X11/Xaw/Panner.h
/usr/include/X11/Xaw/PannerP.h
/usr/include/X11/Xaw/Porthole.h
/usr/include/X11/Xaw/PortholeP.h
/usr/include/X11/Xaw/Repeater.h
/usr/include/X11/Xaw/RepeaterP.h
/usr/include/X11/Xaw/Reports.h
/usr/include/X11/Xaw/Scrollbar.h
/usr/include/X11/Xaw/ScrollbarP.h
/usr/include/X11/Xaw/Simple.h
/usr/include/X11/Xaw/SimpleMenP.h
/usr/include/X11/Xaw/SimpleMenu.h
/usr/include/X11/Xaw/SimpleP.h
/usr/include/X11/Xaw/Sme.h
/usr/include/X11/Xaw/SmeBSB.h
/usr/include/X11/Xaw/SmeBSBP.h
/usr/include/X11/Xaw/SmeLine.h
/usr/include/X11/Xaw/SmeLineP.h
/usr/include/X11/Xaw/SmeP.h
/usr/include/X11/Xaw/StripCharP.h
/usr/include/X11/Xaw/StripChart.h
/usr/include/X11/Xaw/Template.c
/usr/include/X11/Xaw/Template.h
/usr/include/X11/Xaw/TemplateP.h
/usr/include/X11/Xaw/Text.h
/usr/include/X11/Xaw/TextP.h
/usr/include/X11/Xaw/TextSink.h
/usr/include/X11/Xaw/TextSinkP.h
/usr/include/X11/Xaw/TextSrc.h
/usr/include/X11/Xaw/TextSrcP.h
/usr/include/X11/Xaw/Tip.h
/usr/include/X11/Xaw/TipP.h
/usr/include/X11/Xaw/Toggle.h
/usr/include/X11/Xaw/ToggleP.h
/usr/include/X11/Xaw/Tree.h
/usr/include/X11/Xaw/TreeP.h
/usr/include/X11/Xaw/VendorEP.h
/usr/include/X11/Xaw/Viewport.h
/usr/include/X11/Xaw/ViewportP.h
/usr/include/X11/Xaw/XawImP.h
/usr/include/X11/Xaw/XawInit.h
/usr/lib64/libXaw.so
/usr/lib64/libXaw6.so
/usr/lib64/libXaw7.so
/usr/lib64/pkgconfig/xaw6.pc
/usr/lib64/pkgconfig/xaw7.pc
/usr/share/man/man3/Xaw.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libXaw/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXaw.so.6
/usr/lib64/libXaw.so.7
/usr/lib64/libXaw6.so.6
/usr/lib64/libXaw6.so.6.0.1
/usr/lib64/libXaw7.so.7
/usr/lib64/libXaw7.so.7.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXaw/COPYING
